---
# tasks file for lb-tier
- block:
   - name: install HAProxy
     yum:
       name: haproxy 
       state: latest
   - name: enable HAProxy
     service:
       name: haproxy
       state: started
       enabled: true
   - name: configure haproxy
     template:
       src: haproxy.cfg.j2
       dest: /etc/haproxy/haproxy.cfg
     notify: restart_haproxy
  tags:
    - lbs
    - haproxy

